databases:
  - name: sa15-db
    plan: free

services:
  - type: web
    name: sa15-portfolio
    runtime: ruby
    plan: free
    region: ohio
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sa15-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
